version: '3.8'

services:
  # MySQL service for database
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookapi    
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - "3306:3306"

  # Laravel API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: db
      DB_DATABASE: bookapi
      DB_PORT: 3306
      DB_USERNAME: app
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "8000:8000"

  # Nuxt.js client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    environment:
      API_URL: http://api:8000
    networks:
      - my_network
    ports:
      - "3000:3000"

  # Nginx reverse proxy service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl  # نشر الشهادات إلى الحاوية
    networks:
      - my_network
    depends_on:
      - client
    ports:
      - "80:80"
      - "443:443"

networks:
  my_network:
    driver: bridge

volumes:
  db_data: 
